spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3145961181f
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9292